//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int Id { get; set; }
        public string FuelType { get; set; }
        public int FuelPrice { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
